"""Generates every launcher icon for both apps from one description of the mark.

Run:  python tool/build_app_icons.py

## What the mark is

Two chevrons, ascending, the leading one white. **Run ascends rightward**
because a run is distance; **Lift ascends upward** because a lift is load. The
ground is a linear sweep whose light comes from the heading — one number,
rotated. Everything else about the two apps' icons is identical, which is the
point: they are one family with one difference.

Greyscale throughout, per
[ADR-0009](../apps/mgk_run/docs/decisions/0009-greyscale-design-language.md) —
colour is reserved for status and an app icon is not a status.

## Why this is a generator rather than a folder of PNGs

Twenty-nine files per app, at nine sizes, across three Android layers and
nineteen iOS slots. Hand-exported, they drift: someone nudges the mark, regens
four of them, and the 48dp icon stops matching the 1024 one. Here the geometry
exists once and every size is a render of it.

It also makes the design reviewable. The exploration that led to this mark is
in `apps/mgk_run/design/icon-candidates/`, including the rejected directions
and the two that failed outright.

## The three Android layers

Android 8+ composes an **adaptive icon** from two layers, each a 108dp canvas of
which only the central 66dp is guaranteed to survive the launcher's mask:

  * `ic_launcher_foreground` — the mark, transparent around it, drawn inside
    the safe circle.
  * `ic_launcher_background` — the sweep, full bleed, meant to be cropped.
  * `ic_launcher_monochrome` — the mark as a single-colour silhouette, which
    Android 13+ tints to the system palette for themed icons. Without it the
    app opts out of themed icons and looks dated beside everything else.

`ic_launcher.png` is still written for Android 7 and below, which has no
adaptive icon and shows a plain square.

**Neither of these apps had any of it.** Both shipped Flutter's template logo,
and with no adaptive icon declared the launcher shrank that square onto a white
plate. Run's iOS icon was a real mark that had simply never been ported; Lift
had nothing on either platform.

## Banding

#1A1A1A to #3A3A3A is 32 steps of 8-bit grey stretched across the tile, so a
naive sweep bands — measured at 20 distinct levels with flat stripes up to 56px
wide, which on a 1024px store tile reads as a compression artefact. The sweep is
computed in float and ordered-dithered against an 8x8 Bayer threshold, turning
the error into a stipple no contrast stretch brings back as stripes.
"""

from PIL import Image, ImageDraw
import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SS = 8                      # supersample for the mark
BASE = 1024                 # the canvas everything is rendered at
SAFE = 0.61                 # the mark occupies this much of the canvas
DARK, LIGHT = 0x1A, 0x3A    # AppColors.bg, lifted toward AppColors.elevated
SILVER = (0xC0, 0xC0, 0xC0, 255)
WHITE = (0xFF, 0xFF, 0xFF, 255)

# Run travels right and climbs; Lift climbs. The light comes from the heading.
HEADING = {'run': -25.0, 'lift': -90.0}

BAYER8 = [
    [0, 32, 8, 40, 2, 34, 10, 42], [48, 16, 56, 24, 50, 18, 58, 26],
    [12, 44, 4, 36, 14, 46, 6, 38], [60, 28, 52, 20, 62, 30, 54, 22],
    [3, 35, 11, 43, 1, 33, 9, 41], [51, 19, 59, 27, 49, 17, 57, 25],
    [15, 47, 7, 39, 13, 45, 5, 37], [63, 31, 55, 23, 61, 29, 53, 21],
]

# Android density buckets: (folder, legacy px, adaptive px). Adaptive layers are
# 108dp, legacy launcher icons 48dp, at the bucket's scale factor.
DENSITIES = [
    ('mdpi', 48, 108), ('hdpi', 72, 162), ('xhdpi', 96, 216),
    ('xxhdpi', 144, 324), ('xxxhdpi', 192, 432),
]

ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tool/build_app_icons.py. Do not edit; edit the generator. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />
</adaptive-icon>
"""


# ── The mark ────────────────────────────────────────────────────────────────
def mark(app, size, mono=False):
    """Two chevrons on transparent, drawn big and brought down.

    `mono` flattens both to opaque white: the themed-icon layer is tinted by
    the system to a single colour, so a silver/white distinction there would
    be thrown away and the dimmer chevron would only lose contrast.
    """
    up = app == 'lift'
    c = size * SS
    im = Image.new('RGBA', (c, c), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    w = c * SAFE
    cx = cy = c / 2
    stroke = c * 0.090
    half, lean, gap, rise = w * 0.215, w * 0.200, w * 0.360, w * 0.215

    def stroked(pts, colour):
        for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
            d.line([(x0, y0), (x1, y1)], fill=colour, width=int(stroke))
        for x, y in pts:
            d.ellipse((x - stroke / 2, y - stroke / 2,
                       x + stroke / 2, y + stroke / 2), fill=colour)

    for i, colour in enumerate((SILVER, WHITE)):
        if mono:
            colour = WHITE
        if up:
            x, y = cx - half, cy + gap / 2 - i * gap
            stroked([(x, y), (x + half, y - lean), (x + half * 2, y)], colour)
        else:
            x = cx - gap / 2 - lean / 2 + i * gap
            y = cy + rise / 2 - i * rise
            stroked([(x, y - half), (x + lean, y), (x, y + half)], colour)
    return im.resize((size, size), Image.LANCZOS)


# ── The ground ──────────────────────────────────────────────────────────────
def sweep(app, size, top=0.58):
    """G4: a linear ramp on the heading, computed in float and dithered.

    Linear rather than a wedge or a radial on purpose. A wedge is thrown from
    the tile's centre, so a circular mask and a squircle mask crop it
    differently and the icon changes character between launchers. A linear ramp
    has no focal point to lose and looks the same under every mask.
    """
    angle = math.radians(HEADING[app])
    dx, dy = math.cos(angle), math.sin(angle)
    corners = [0.0, size * dx, size * dy, size * (dx + dy)]
    lo, hi = min(corners), max(corners)
    rng = (hi - lo) or 1.0
    span = LIGHT - DARK

    px = bytearray(size * size)
    for y in range(size):
        row = y * size
        brow = BAYER8[y & 7]
        for x in range(size):
            t = ((x * dx + y * dy) - lo) / rng
            v = DARK + span * (top * t)
            base = int(v)
            px[row + x] = base + (1 if (v - base) * 64 > brow[x & 7] else 0)
    return Image.frombytes('L', (size, size), bytes(px)).convert('RGBA')


def composed(app, size):
    """Ground and mark together — the legacy icon, iOS, and the store tile."""
    g = sweep(app, size)
    g.alpha_composite(mark(app, size))
    return g


# ── Writers ─────────────────────────────────────────────────────────────────
def write(im, path, opaque=False):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if opaque:
        # iOS rejects an icon with an alpha channel outright, and a store tile
        # with one renders on whatever the page background happens to be.
        flat = Image.new('RGB', im.size, (DARK, DARK, DARK))
        flat.paste(im, (0, 0), im)
        flat.save(path)
    else:
        im.save(path)
    return path


def build_android(app, app_dir):
    res = os.path.join(app_dir, 'android', 'app', 'src', 'main', 'res')
    written = []
    for folder, legacy_px, adaptive_px in DENSITIES:
        out = os.path.join(res, 'mipmap-' + folder)
        written.append(write(composed(app, legacy_px),
                             os.path.join(out, 'ic_launcher.png')))
        written.append(write(mark(app, adaptive_px),
                             os.path.join(out, 'ic_launcher_foreground.png')))
        written.append(write(sweep(app, adaptive_px),
                             os.path.join(out, 'ic_launcher_background.png')))
        written.append(write(mark(app, adaptive_px, mono=True),
                             os.path.join(out, 'ic_launcher_monochrome.png')))
    anydpi = os.path.join(res, 'mipmap-anydpi-v26')
    os.makedirs(anydpi, exist_ok=True)
    for name in ('ic_launcher.xml', 'ic_launcher_round.xml'):
        path = os.path.join(anydpi, name)
        with open(path, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(ADAPTIVE_XML)
        written.append(path)
    return written


def build_ios(app, app_dir):
    """Every slot named by the existing Contents.json, at size x scale."""
    aset = os.path.join(app_dir, 'ios', 'Runner', 'Assets.xcassets',
                        'AppIcon.appiconset')
    manifest = os.path.join(aset, 'Contents.json')
    with open(manifest, encoding='utf-8') as fh:
        images = json.load(fh)['images']
    done, written = set(), []
    for entry in images:
        name = entry.get('filename')
        if not name or name in done:
            continue
        done.add(name)
        w = float(entry['size'].split('x')[0])
        px = int(round(w * float(entry['scale'].rstrip('x'))))
        written.append(write(composed(app, px), os.path.join(aset, name),
                             opaque=True))
    return written


def build_store(app, app_dir):
    """The 512px Play listing tile. Uploaded by hand; not part of the bundle."""
    out = os.path.join(app_dir, 'design', 'store')
    return [write(composed(app, 512),
                  os.path.join(out, 'play-listing-icon-512.png'), opaque=True)]


def main():
    apps = sys.argv[1:] or ['run', 'lift']
    for app in apps:
        app_dir = os.path.join(ROOT, 'apps', 'mgk_' + app)
        if not os.path.isdir(app_dir):
            print('skip', app, '(no such app)')
            continue
        n = 0
        for builder in (build_android, build_ios, build_store):
            n += len(builder(app, app_dir))
        print(f'{app:5} {n:3} files')


if __name__ == '__main__':
    main()
