"""Render Lift's legal documents to the pages served at mgkfitness.mgkcodes.com/lift.

Run from `apps/mgk_lift`:

    python tool/build_legal_pages.py

Writes `web/public/lift/{privacy-policy,terms-of-use,ai-disclosure}.html`, which
`web/next.config.ts` serves at `/lift/privacy`, `/lift/terms` and
`/lift/ai-disclosure`. Regenerate after any edit to the three documents; the
legal test fails if the served pages stop carrying what the app says.

**Run's renderer, not a copy of it.** Both apps publish their documents the same
way, and two renderers is two chances for one app's page to render a list or an
emphasis differently from the other's. This imports
`apps/mgk_run/tool/build_legal_pages.py` and uses its `render` and `CSS`.

**What this adds: HTML comments are stripped.** Lift's documents carry their
repo notes in `<!-- -->` blocks (the draft banners moved there on 2026-09-02).
They do not render in markdown, but Run's renderer reads a line at a time and
would print them as paragraphs, and a page reading "NOT FOR PUBLICATION" is not
a privacy policy.
"""

from __future__ import annotations

import html
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
# Importing Run's script would otherwise leave a __pycache__ in Run's tool/,
# which nothing ignores and nobody means to commit.
sys.dont_write_bytecode = True
sys.path.insert(0, str(HERE.parents[1] / "mgk_run" / "tool"))
import build_legal_pages as shared  # noqa: E402  (Run's renderer, see above)

DOCS = pathlib.Path("docs")
WEB = pathlib.Path("../../web/public/lift")

PAGES = [
    ("privacy-policy.md", "privacy-policy.html"),
    ("terms-of-use.md", "terms-of-use.html"),
    ("ai-disclosure.md", "ai-disclosure.html"),
]

COMMENT = re.compile(r"<!--.*?-->", re.S)


def build(src_name: str, out_name: str) -> str:
    md = COMMENT.sub("", (DOCS / src_name).read_text(encoding="utf-8"))
    title, body = shared.render(md)
    page = f"""<!doctype html>
<!--
  GENERATED by apps/mgk_lift/tool/build_legal_pages.py from
  apps/mgk_lift/docs/{src_name}. Do not edit this file: edit the source and
  regenerate, or the app, the repository and this page stop agreeing, which is
  exactly what App Store review checks.
-->
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<style>{shared.CSS}</style>
</head>
<body>
<main>
<h1>{html.escape(title)}</h1>
{body}
<footer>MGKCodes Ltd &middot; <a href="mailto:hello@mgkcodes.com">hello@mgkcodes.com</a></footer>
</main>
</body>
</html>
"""
    WEB.mkdir(parents=True, exist_ok=True)
    (WEB / out_name).write_text(page, encoding="utf-8", newline="\n")
    return "%s  (%.1f KB)  <- docs/%s" % (out_name, len(page) / 1024, src_name)


if __name__ == "__main__":
    if not (DOCS / "ai-disclosure.md").is_file():
        sys.exit("run this from apps/mgk_lift")
    for src, dst in PAGES:
        print(build(src, dst))
