import type { NextConfig } from "next";
import path from "node:path";

// Same three as the studio site. A legal page that can be framed is a legal
// page somebody can present as their own.
const securityHeaders = [
  { key: "X-Frame-Options", value: "DENY" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
];

const nextConfig: NextConfig = {
  // Pin Turbopack's workspace root. Without it Turbopack walks up into the
  // Flutter monorepo above this directory and resolves modules against the
  // wrong tree. The studio site needs the same pin for the same reason.
  turbopack: {
    root: path.resolve(__dirname),
  },
  async headers() {
    return [{ source: "/:path*", headers: securityHeaders }];
  },
  // The legal pages are not React. They are complete, self-contained documents
  // written into `public/` by `apps/mgk_run/tool/build_legal_pages.py`, from
  // the same markdown the in-app copy is pinned to.
  //
  // **Serving the generated bytes, rather than a component that reproduces
  // them, is the entire point.** App Review compares the published page against
  // what the app shows, word for word. A React page would be a fourth rendering
  // of a text that already exists three times, and the fourth is the one no
  // test can see. `legal_copy_test.dart` reads the file these rewrites serve.
  //
  // The extension is hidden because a URL with `.html` in it looks like
  // something that might move, and this one goes in an App Store listing that
  // cannot be corrected without a new submission.
  async rewrites() {
    return [
      { source: "/run/privacy", destination: "/run/privacy-policy.html" },
      {
        source: "/run/medical-disclaimer",
        destination: "/run/medical-disclaimer.html",
      },
    ];
  },
  // One URL per document. Files in `public/` are served at their own path
  // whether or not anything rewrites to them, so without these the privacy
  // policy answers at two addresses and the wrong one is exactly as easy to
  // copy into App Store Connect as the right one. Redirects run before
  // rewrites, and a rewrite does not re-enter the redirect phase, so these do
  // not loop back on the rules above.
  async redirects() {
    return [
      {
        source: "/run/privacy-policy.html",
        destination: "/run/privacy",
        permanent: true,
      },
      {
        source: "/run/medical-disclaimer.html",
        destination: "/run/medical-disclaimer",
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
