import type { NextConfig } from "next";
import path from "node:path";

// Only the studio site may frame this one: mgkcodes.com shows the suite running
// live on its home page. Every other site is still refused, legal pages
// included, because a legal page that can be framed is a legal page somebody
// can present as their own. frame-ancestors replaces X-Frame-Options, which
// cannot name an allowed site.
const securityHeaders = [
  {
    key: "Content-Security-Policy",
    value: "frame-ancestors 'self' https://mgkcodes.com https://www.mgkcodes.com",
  },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
];

const nextConfig: NextConfig = {
  // Pin Turbopack's workspace root. Without it Turbopack walks up into the
  // Flutter monorepo above this directory and resolves modules against the
  // wrong tree. The studio site needs the same pin for the same reason.
  turbopack: {
    root: path.resolve(__dirname),
  },
  async headers() {
    return [{ source: "/:path*", headers: securityHeaders }];
  },
  // The legal pages are not React. They are complete, self-contained documents
  // written into `public/` by `apps/mgk_run/tool/build_legal_pages.py`, from
  // the same markdown the in-app copy is pinned to.
  //
  // **Serving the generated bytes, rather than a component that reproduces
  // them, is the entire point.** App Review compares the published page against
  // what the app shows, word for word. A React page would be a fourth rendering
  // of a text that already exists three times, and the fourth is the one no
  // test can see. `legal_copy_test.dart` reads the file these rewrites serve.
  //
  // The extension is hidden because a URL with `.html` in it looks like
  // something that might move, and this one goes in an App Store listing that
  // cannot be corrected without a new submission.
  async rewrites() {
    return [
      { source: "/run/privacy", destination: "/run/privacy-policy.html" },
      {
        source: "/run/medical-disclaimer",
        destination: "/run/medical-disclaimer.html",
      },
      // `/run/terms` is load-bearing in a way the other two are not: the app
      // LINKS to it rather than rendering it, so this rewrite is the whole
      // document as far as a runner is concerned. It is also the URL that goes
      // in the Play listing's terms field and App Store Connect's EULA field,
      // neither of which can be corrected without a resubmission.
      { source: "/run/terms", destination: "/run/terms-of-use.html" },
      // Lift's three, written by apps/mgk_lift/tool/build_legal_pages.py with
      // Run's renderer. Lift renders its terms in the app as well as linking
      // them, so all three are pinned by Lift's legal_copy_test.dart.
      { source: "/lift/privacy", destination: "/lift/privacy-policy.html" },
      { source: "/lift/terms", destination: "/lift/terms-of-use.html" },
      {
        source: "/lift/ai-disclosure",
        destination: "/lift/ai-disclosure.html",
      },
    ];
  },
  // One URL per document. Files in `public/` are served at their own path
  // whether or not anything rewrites to them, so without these the privacy
  // policy answers at two addresses and the wrong one is exactly as easy to
  // copy into App Store Connect as the right one. Redirects run before
  // rewrites, and a rewrite does not re-enter the redirect phase, so these do
  // not loop back on the rules above.
  async redirects() {
    return [
      {
        source: "/run/privacy-policy.html",
        destination: "/run/privacy",
        permanent: true,
      },
      {
        source: "/run/medical-disclaimer.html",
        destination: "/run/medical-disclaimer",
        permanent: true,
      },
      {
        source: "/run/terms-of-use.html",
        destination: "/run/terms",
        permanent: true,
      },
      {
        source: "/lift/privacy-policy.html",
        destination: "/lift/privacy",
        permanent: true,
      },
      {
        source: "/lift/terms-of-use.html",
        destination: "/lift/terms",
        permanent: true,
      },
      {
        source: "/lift/ai-disclosure.html",
        destination: "/lift/ai-disclosure",
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
